nome = input ("Qual é o seu nome? " ) 
idade = input (" Qual é a sua idade? " )
peso = input ("Qual é o seu peso? " )
pergunta1 = input ('O que gostaria de aprender hoje? ')
pergunta2 = input ('O que você sabe de inglês? ')
pergunta3 = input ('Qual é o seu nivel de inglês? ')
pergunta4 = input ('De 0 a 10 qual seria sua vontade de aprender inglês? ')
pergunta5 = input ('você pratica o seu inglês em qual app? ')
pergunta6 = input ('você já estudou hoje? ') 
pergunta7 = input ('você gostaria de prender? ')
print(nome, idade, peso, pergunta1, pergunta2, pergunta3, pergunta4, pergunta5, pergunta6, pergunta7)